### ISSUE TITLE
项目很棒,有 demo 的示例吗

### ISSUE THREAD

**Issue by zhaopengme** [bysir-zl/go-vue-ssr#1]
最近也在研究这块,有 demo 的示例吗

**Comment by bysir-zl** [comment]
正在写文档咯

**Comment by bysir-zl** [comment]
> 最近也在研究这块,有 demo 的示例吗

正在写文档咯

**Comment by bysir-zl** [comment]
> 最近也在研究这块,有 demo 的示例吗

已添加文档: https://bysir-zl.github.io/go-vue-ssr/#example--usage, 以及例子: https://github.com/bysir-zl/go-vue-ssr/tree/master/example/helloworld
